site_name: AFASTGRok MESH
site_url: https://amora.github.io/AFASTGRok-MESH-/
site_author: analystcode
site_description: Planetary-Scale Decentralized AI Video Delivery Network

repo_url: https://github.com/analystcode/AFASTGRok-MESH-
repo_name: analystcode/AFASTGRok-MESH-
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
  favicon: assets/logo.png

plugins:
  - search
  - mkdocstrings
  - git-revision-date-localized:
      type: timeago

extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX   # add later if you want
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/analystcode
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourhandle

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Whitepaper (PDF): https://github.com/analystcode/AFASTGRok-MESH-/raw/main/FASTGRok_MESH_Whitepaper_v1.1.pdf
  - Architecture: architecture.md
  - Tokenomics ($MESH): tokenomics.md
  - ISP Partnership Playbook: isp-partnership.md
  - Security & Privacy: security.md
  - Roadmap: roadmap.md
  - Download PDF: https://github.com/analystcode/AFASTGRok-MESH-/releases/latest
